apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aks-ingress-contoso-com-tls-secret-csi-akv
  namespace: a0008
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: $KEYVAULT_NAME
    objects: |
      array:
        - |
          objectName: wildcard-ingress
          objectAlias: tls.crt
          objectType: cert
        - |
          objectName: wildcard-ingress
          objectAlias: tls.key
          objectType: secret
    tenantId: $TENANTID_AZURERBAC
